### ISSUE TITLE
failed to download box as DEFAULT_SERVER_URL has changed

### ISSUE THREAD

**Issue by raghavendra-talur** [sclorg-distgit/vagrant#3]
It seems vagrant boxes can no longer be downloaded from  "https://atlas.hashicorp.com" and all boxes should be downloaded from https://vagrantcloud.com. This change was done in https://github.com/hashicorp/vagrant/commit/5f955c3d38f27a036e3eb569ad17494afe293a21 . If this is the right repo for building vagrant rpms for scl, then can we have a rpm with the commit mentioned above?

**Comment by pvalena** [comment]
Rebase to v1.9.8, or similar, is planned instead.
Please be patient.
As a workaround, in the meantime, you can define:

`ENV["VAGRANT_SERVER_URL"]`

HIH,
Pavel
